rave_python/rave_subscription.py

Incorrect stringified variable in Subscription class methods corrected. This closes #28 (Wrong variable passed in Subscriptions class methods cancelSubscription and fetchSubscription).

Updated rave_subscription.py

---

.gitignore

Test file for francophone mobile money has been removed.

franc_test.py removed

---

README.md
rave_python/rave.py
rave_python/rave_base.py
rave_python/rave_exceptions.py
rave_python/rave_virtualcard.py
virtualCardTest.py

Updates the readme file. Added Create and list functions for virtual cards

Virtual card class 

---

rave_base.py
rave_virtualcard.py

Added cancel, get card, freeze and unfreeze card functions in the virtual card class. Edited virtual card endpoints in base class.

Updated base and virtual card classes

---

.github/ISSUE_TEMPLATES/bug_report.md
.github/ISSUE_TEMPLATES/feature_request.md
.github/ISSUE_TEMPLATES/other_issues.md
.github/PULL_REQUEST_TEMPLATE.md

Adding pull request template and issue templates

---

rave_python/__init__.py

Refer to
https://github.com/Flutterwave/rave-python/blob/be98ebfcc9e1c06e31b0b2127aa41921950b65f1/setup.py#L8
*

bump version for consistency

---

README.md

With this PR code snippets in README renders with Python markdown, which is much prettier and allows to read them faster.
For example:
*

added Python markdown to README

---

README.md

fixed txRef highlight. Add extra backtick (`)
Added extra backtick (``` ` ```) to fix one instance of non-highlighted 'txRef'
* fixes #48

Update README - fix txRef highlight

---

rave_python/rave.py

Refactored rave.py

---

rave_python/rave_account.py

Refactored Rave account

---

README.md

Updated README to provide proper markdown links for all references to the Misc library, replacing all `(add link)` placeholders with link to `rave_misc.py` library file.
*

Added proper links for misc library in README

---

rave_python/rave_card.py

Created temporal fix for parsing error
*

Temporal parsing fix for rave_card.py

---

README.md
rave_python/rave.py
rave_python/rave_base.py
rave_python/rave_bills.py
rave_python/rave_exceptions.py
rave_python/rave_paymentplan.py
rave_python/rave_recepient.py
rave_python/rave_recipient.py
rave_python/rave_settlement.py
rave_python/rave_subaccounts.py
rave_python/rave_subscription.py
rave_python/rave_transfer.py
rave_python/rave_verify.py
rave_python/rave_virtualaccount.py
rave_python/rave_virtualcard.py

New features were added to the already existing ones. The codebase was reviewed to make it easier for developers to use.
- BVN verification and transfer recipient classes were added.
- Update and delete features were added to subaccount class.
- Function names in Bills, Payment plan, Settlement, Sub Accounts, Subscription, Transfers, Virtual account and Virtual card superclasses were reviewed to make the codebase easier to use.

Features updates

---

.gitignore
README.md
test.py

Added new test suites for the newly added features. 
*

Updated Test scripts

---

rave_python/rave_misc.py
rave_python/rave_settlement.py
rave_python/rave_virtualaccount.py
rave_python/rave_virtualcard.py

Fix few typos

---

rave_python/rave_mpesa.py

Fixed session timeout for transaction 
* Closes #55

Updated Mpesa Superclass

---

rave_python/rave_payment.py

Added new files to handle new Momo flow for mobile money transactions.
Closes #75 
This change has been tested for GHS, RWF, UGX and ZMW mobile money payments
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x ] Non-functional change (xml comments/documentation/etc)
- [ x ] My code follows the code style of this project.
- [ x ] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ x ] All new and existing tests passed.
@Flutterwave/Corvus97 What do you think about these updates?

added files for MOMO transactions

---

README.md

instead of account the payload parameter should be amount and not account as indicated

Mpesa payload parameter

---

rave_python/rave_francophone.py
rave_python/rave_payment.py
rave_python/rave_preauth.py
rave_python/rave_ugmobile.py
setup.py
virtualCardTest.py

Fixed bugs in mobile money uganda. Made redirect url an optional paramater.
Users were unable to charge mobile money UG. After review, I identified and fixed the bug causing the error in the payment flow. was also able to update response format to match the update.
@Flutterwave/Corvus97 What do you think about these updates?

fixed bug with mobile-money-uganda

---

README.md
rave_python/rave_francophone.py
rave_python/rave_payment.py
rave_python/rave_preauth.py
rave_python/rave_ugmobile.py
setup.py
test.py
virtualCardTest.py

@Flutterwave/Corvus97 What do you think about these updates?

updated staging branch

---

rave_python/rave_base.py
setup.py

@Flutterwave/Corvus97 What do you think about these updates?

bumped version and updated tracking endpoint

---

rave_python/rave_francophone.py
rave_python/rave_transfer.py

Include support for paginated data queries on the bulk transfer method. This closes #95.

Add support for pagination on bulk transfer query
